# Generated by Django 5.0.7 on 2024-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
