# Generated by Django 5.0.7 on 2024-08-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_modify_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modify_date',
            new_name='updated_at',
        ),
    ]
